### ISSUE TITLE
The role of trauma

### ISSUE THREAD

**Issue by cgutshal** [tenebrouspress/mud#2]
What is trauma being used to represent?

**Comment by abutcher** [comment]
@cgutshal I think this is mental state.

**Comment by cgutshal** [comment]
@abutcher Ah so like. You see a spooky ghost (-1 Trauma). Correct?

**Comment by abutcher** [comment]
Like you just saw the birth of a god, roll 1d100 sanity loss.

**Comment by cgutshal** [comment]
10/4 Closing this since that is cleared up.
